title: "Portfolio Yannick"
description: "Étudiant ingénieur spécialisé en systèmes, réseaux et cybersécurité"
logo: img/pp.jng
show_download: true

# Paramètres GitHub Pages
theme: jekyll-theme-midnight   # tu peux choisir un autre thème supporté par Jekyll
lang: fr
